### ISSUE TITLE
#1 Logic error

### ISSUE THREAD

**Issue by bigmosi** [aliatayee/catalog-of-my-things#34]
## `can_be_archived?`  error in `Item` class
- Fix the return statement

## `add_label` error in `Item` class
>def add_label(label)
 >   @label = label
>    genre.add_item(self) unless @genre.items.include?(self)
 > end

**Or**

>  def add_label(label)
 >   @label = label
 >   label.add_item(self) unless @label.items.include?(self)
>  end

**Comment by RitobrotoMukherjee** [comment]
It should be

>def add_label(label)
 >   @label = label
 >   label.add_item(self) unless @label.items.include?(self)
> end

That's a typo.
